# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# rate = Ratings.create(number: 0)
FoodTruck.create(name: 'Casablanca', cuisine: 'Middle Eastern', desc:'Casablanca continues the tradition started by Rosas of having Asian women cooking non-Asian food.', location: '36th and Spruce',  open: 11, close: 12)
FoodTruck.create(name: 'Yue Kee', cuisine: 'Chinese', desc:'Okay, so you know that thing where things become so heralded for being underrated that they become overrated? Yue Kee\'s has it. While there is no doubting the quality and quantity of the food, there is also no doubt that food takes forever to get to you (even if you call ahead) and the owners are always grouchy. Oh, and did we mention that you can get the same thing a couple blocks away for a dollar cheaper on average? But since everyone from the DP to Wharton professors have called this place great - you can carry on waiting in line.', location: '38th and Walnut', open: 11, close: 21)
FoodTruck.create(name: 'Lovash', cuisine: 'Indian', desc:'Lovash is the new food truck by the owners of Lucky\'s -- the Mexican truck a bit to the east on Spruce. This truck, like Lucky\'s, is backed up by a full-service restaurant on South Street. While the food does not compare to some of the high-quality Indian fair available in Center City, it is more than decent and serves as a welcome addition to the lack of Indian options on campus', location: '37th and Spruce', open: 10, close: 15)
FoodTruck.create(name: 'Curry on Wheels', cuisine: 'Indian', desc: 'Here\'s the True Taste of India brought to you by Curry on Wheels!
Started by Silicon Valley Entrepreneurs (foodies!) & Chefs, Curry on Wheels offers a variety of choicest authentic regional Indian food combined with extraordinary service levels.Be it delivery for your private event or take-out, we offer you the true taste of Authentic Indian-Food (free from creme, stereotypical gravy & food colors). Specialties include Cutlets, Kathi Rolls, authentic gravy based Curries & mouth-watering Desserts.', location: '37th and Walnut', open: 11, close: 20)
FoodTruck.create(name: 'The Real Le Anh', cuisine: 'Chinese', desc: 'Yes, this is actually the real one. The rumor about a sibling fight is not real and the truth is more boring. Le Ahn had two trucks on campus, sold one to her friend (Le Ahn\'s) and kept one (The Real Le Ahn\'s). You can blame the antagonistic name on Chinglish. Anyway, the food selection is ordinary and like her friend across the street, a healthy lump of generic sauce is dumped on each dish. However, she\'s the friendlier of the two and if you want Pad Thai or Bubble Tea without getting seated, this is one of the only places to go. Warning: Don\'t get the small size unless you are flat out broke.', location: '36th and Spruce', open: 11, close: 21)
FoodTruck.create(name: 'Bui\'s', cuisine: 'American', desc: 'Bui\'s has become the quintessential college meeting place on weekend mornings as students from all over campus stop by to get Bui\'s famous Hangover Special. Operated by a quiet, but friendly Vietnamese couple, Bui\'s prices are usually reasonable but may be inflated over other similar trucks (like neighboring Steak Queen) as it appears that this is the only truck known to everyone on campus. Still, Bui\'s is a great stop for breakfast and lunch sandwiches and is open seven days a week starting at 7am.', location: '38th and Spruce', open: 7, close: 16)
FoodTruck.create(name: 'Hemo\'s', cuisine: 'American', desc: 'Widely considered the best grilled chicken sandwich on campus. Hemo\'s sauce makes the sandwich, which is very tasty. Sandwiches can get pricey if you want lettuce tomato, onions, and anything else, as you have to pay for each topping. Don\'t bother going for lunch if you are short on time.', location: '37th and Spruce', open: 7, close: 15)
FoodTruck.create(name: 'Fruit At 33rd/Spruce', cuisine: 'Fruit', desc: 'Typical fruit truck, but located all the way near the hospital. One of the few fruit trucks that still only charges 2.50 for a small.', location: '33rd and Spruce', open: 7, close: 16)
FoodTruck.create(name: 'Fruit At 34th/Spruce', cuisine: 'Fruit', desc: 'This fruit truck has the best mango slices almost all of the time. They cut them very well, at just the right ripeness, and give you a banana too. Great if you like mango.', location: '34th and Spruce', open: 7, close: 9)
FoodTruck.create(name: 'Dulett\'s Jamaica Wings', cuisine: 'Jamaican', desc: 'They have a really good Jamaican Jerk Chicken Sandwich here. A little pricey ($5.50) but huge - lots and lots of pieces of real chicken breast and really good jerk sauce.', location: '38th and Locust', open: 14, close: 21)
FoodTruck.create(name: 'GiGi\'s and Big R', cuisine: 'Jamaican', desc: 'I had heard good things about this cart before trying it out myself, and I can now definitely say that everything good you have heard about it is well-deserved. The service can be a little bit slow, but it is well worth the wait - the food is absolutely fantastic and full of flavor, and the portion sizes are good.', location: '38th and Spruce', open: 11, close: 20)
FoodTruck.create(name: 'MexiCali', cuisine: 'Mexican', desc: 'Generic mexican fare, from the same owners as the MexiCali restaurant on 40th street. You can customize the burritos with plantains, sweet potatoes or roasted peppers, or sour cream and guacamole. Each addition adds quite a bit to the cost though so expect to pay more than five bucks. Beware, if you want a hot burrito that still has chunky salsa on it, you have to say hot and mild.', location: '38th and Walnut', open: 11, close: 16)
FoodTruck.create(name: 'Honest Tom\'s Taco Shop', cuisine: 'Mexican', desc: 'Honest Tom\'s is a very unique food truck on Drexel\'s campus. It features quality Mexican fare with just two or three items. Vegetarian tacos are $2 each and meat tacos are $3.5 (or $6 for 2). The truck is run by two twenty-something guys and the food always tastes fresh and delicious. Come by early for breakfast tacos (fried eggs mixed in) or visit them on Saturdays at Clark Park (42nd and Chester).', location: '33rd and Arch', open: 8, close: 15)
FoodTruck.create(name: 'Troy Mediterranean', cuisine: 'Middle Eastern', desc: 'Great intepretation of the NYC Halal cart concept', location: '38th and Spruce', open: 10, close: 12)
FoodTruck.create(name: 'Magic Carpet at 34th/Walnut', cuisine: 'Vegetarian', desc: 'Best vegetarian option on campus. Lines can be brutal, and for the amount of food, the price is a little high. Taste is great though and there are a variety of options.', location: '34th and Walnut', open: 11, close: 16)
FoodTruck.create(name: 'Magic Carpet at 36th/Spruce', cuisine: 'Vegetarian', desc: 'Founded in 2007, Magic Carpet is a destination for simple, seasonal, healthy food. We believe the choices we make about what we eat, where it comes from and how it’s prepared have a direct and powerful impact on the health of individuals, communities and the environment. That’s why we’re building a transparent supply network, why we cook from scratch, and why we’re building a community of people who support real food. We’re in the business of feeding people, and we’re out to change what that means.', location: '36th and Spruce', open: 11, close: 15)